- name: Setup webservers
  hosts: webservers
  become: yes
  tasks:
    - name: Update Apt cache
      ansible.builtin.apt:
        update_cache: yes
      tags:
        - update_cache

    - name: Install git
      ansible.builtin.apt:
        name: git
        state: present
      tags:
      - install_git
